name: 'CI/CD workflow for feature branches'

on:
  push:
    branches: ['feature/**']
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: ['main']

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI workflow for feature branches..."
  CD:
    runs-on: ubuntu-latest
    environment: 'Dev'
    steps:
      - run: echo "CD workflow for feature branches"