name: 'CD workflow for feature branches'

on:
  pull_request:
    branches: ['main']

jobs:
  Dev-CD:
    runs-on: ubuntu-latest
    environment: 'Dev'
    steps:
      - run: echo "CD workflow for feature branches"