name: 'CI workflow for feature branches'

on:
  push:
    branches: ['feature/**']
    paths-ignore:
      - '.github/**'

jobs:
  Dev-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI workflow for feature branches..."
