name: 'CD workflow for main branch'

on:
  push:
    branches: 
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  Prod-CD:
    runs-on: ubuntu-latest
    environment: 'Prod'
    steps:
      - run: echo "CD workflow for main branch"
